#!/bin/bash
TARGET="/bigtoolhub.alprointerbiz.com"
GIT_DIR="/home1/alpro2dd/repos/big-tool-hub.git"
BRANCH="master"

while read oldrev newrev ref
do
    if [[ $ref = refs/heads/$BRANCH ]];
    then
        echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
        cd $TARGET
        composer install --no-dev
        php artisan migrate --force
        echo "Deployment finished."
    fi
done
